<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Tarefa extends Model
{
    use HasFactory;

    protected $fillable = ['titulo', 'status', 'descricao'];

    protected $attributes = [
        'status' => 0,
    ];

    public static $statusList = [
        'pendente'     => 0,
        'em_andamento' => 1,
        'finalizada'   => 2,
    ];

    //region Overrides
    public function save(array $options = [])
    {
        if (!$this->id || !$this->user_id) {
            $this->user_id = auth()->user()->id;
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function delete()
    {
        //Remover usuarios relacionados
        $this->users()->sync([]);

        //Remover comentários

        //Continuar
        return parent::delete(); // TODO: Change the autogenerated stub
    }
    //endregion

    //region Relations
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_tarefa', 'tarefa_id', 'user_id')->using(UserTarefa::class);
    }
    //endregion


}
